data:
  type: 'binary'
  n_features: 50
  source: 
    type: 'samples'
    path: 'datasets/data.csv'
  mask:
    distribution: 'uniform'
    params:
      min: 0.1
      max: 0.8
    
model:
  n_features: '${data.n_features}'
  data_type: '${data.type}'
  embedding_dim: 100
  score_function:  'exp'
  context_aggregator: 'avg'
  
train:
  lr: 0.01
  model_path: 'models/model.pth'
  device: 'cuda'
  n_steps: 10000
  load_factor: 5
  batch_size: 1024
  debug:
    print_interval: 10
    save_interval: 50