data:
  dir: 'data'
  path: 'data/3'
  type: 'binary'
  n_features: 25
  load: true
  save: false
  source: 
    type: 'dag'
    edge_probability: 0.2
    max_parents: 10
  mask:
    distribution: 'uniform'
    params:
      min: 0
      max: 1
      eval_size: ${train.eval_size}
  
model:
  n_vocab: 2
  n_features: '${data.n_features}'
  data_type: '${data.type}'
  context_dim: 128
  output:
    n_layers: 4
    hidden_dim: 128
  device: ${train.device}
  eval: ${train.eval}
  
train:
  lr_schedule: [[5000, 0.01], [25000, 0.001]]
  save_dir: 'checkpoints'
  device: mps
  n_steps: 30000
  batch_size: 256
  batches_per_epoch: 50
  eval_size: 2000
  print_log: true
  print_interval: 500
  save_interval: 500
  log_interval: 500
  eval:
    consistency:
      num_permutations: 50
      swap: true
      path: false
      autoregressive: false
  fullcontext: false
