data:
  type: 'discrete'
  n_features: 50
  source: 
    type: 'dag'
    edge_probability: 0.2
  mask:
    distribution: 'uniform'
    params:
      min: 0.1
      max: 0.9
    
model:
  data_type: '${data.type}'
  embedding_dim: 100
  score_function:  'exp'
  context_aggregator: 'avg'
  
train:
  lr: 0.001
  model_path: 'models/model.pth'
  device: 'cpu'
  n_steps: 100
  n_samples: 51200
  batch_size: 512
